# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r_packages:
 - devtools

repos:
  CRAN: https://cloud.r-project.org
  rqtl: http://rqtl.org/qtl2cran

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - Rscript -e 'covr::codecov()'

# only use travis on master branch
branches:
  only:
  - master

# avoid timeout (see <https://github.com/travis-ci/travis-ci/issues/3849#issuecomment-255096774>)
script:
  - |
    travis_wait 30 R CMD build --no-build-vignettes .
    travis_wait 30 R CMD check --no--vignettes *.tar.gz
