---
title: "Profiling `scan_pvl`"
author: "Frederick Boehm"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(qtl2pleio)
```

We want to examine the code within `scan_pvl` to see if we might accelerate its completion. Specifically, we need to focus on the code within the loop over the d-tuples of markers. We've considered, so far, only d = 2, ie, a two-dimensional scan.

## Setup

```{r}
 ## define probs
probs_pre <- rbinom(n = 100 * 10, size = 1, prob = 1 / 2)
probs <- array(data = probs_pre, dim = c(100, 1, 10))
s_id <- paste0('s', 1:100)
rownames(probs) <- s_id
colnames(probs) <- 'A'
dimnames(probs)[[3]] <- paste0('Marker', 1:10)
# define Y
Y_pre <- runif(200)
Y <- matrix(data = Y_pre, nrow = 100)
rownames(Y) <- s_id
colnames(Y) <- paste0('t', 1:2)
covariates <- matrix(c(runif(99), NA), nrow = 100, ncol = 1)
rownames(covariates) <- s_id
colnames(covariates) <- 'c1'
kin <- diag(100)
rownames(kin) <- s_id
colnames(kin) <- s_id
Y2 <- Y
Y2[1, 2] <- NA
```


## Profiling

```{r}
library(lineprof)
```

```{r}
(out <- lineprof(scan_pvl(probs = probs, 
                   pheno = Y, 
                   kinship = kin,
                   start_snp = 1, 
                   n_snp = 10
                   )
          )
 )

```

```{r}
library(tidyverse)
```

```{r}
out %>%
  as_tibble() %>%
  arrange(desc(time))

```

