#' Calculate log likelihood for a bivariate linear mixed effects model
#'
#' @param X a block-diagonal, 2n by 2f design matrix containing genotype probabilities for two markers
#' @param Bhat a vector of estimated allele effects. Can be generated by as.vector(B), where B is f by 2
#' @param Y a n by 2 matrix of phenotype values
#' @param Sigma a 2n by 2n covariance matrix.
#'
#' @name calc_loglik_bvlmm-deprecated
#' @usage calc_loglik_bvlmm(X, Bhat, Y, Sigma)
#' @seealso \code{\link{qtl2pleio-deprecated}}
#' @keywords internal
NULL

#' @rdname qtl2pleio-deprecated
#' @section \code{calc_loglik_bvlmm}:
#' For \code{calc_loglik_bvlmm}, use \code{\link{mvtnorm::dmvnorm}}.
#'
#' @export

calc_loglik_bvlmm <- function(X, Bhat, Y, Sigma) {
    .Deprecated(new = "dmvnorm", package = "mvtnorm")
    out <- mvtnorm::dmvnorm(as.vector(Y), mean = X %*% Bhat, sigma = Sigma, log = TRUE)
    return(out)
}
