#' Calculate log likelihood for a bivariate linear mixed effects model
#'
#' @param X a block-diagonal, 2n by 2f design matrix containing genotype probabilities for two markers
#' @param Bhat a vector of estimated allele effects. Can be generated by as.vector(B), where B is f by 2
#' @param Y a 2n by 2 matrix of phenotype values
#' @param Sigma a 2n by 2n covariance matrix.
#' @export

calc_loglik_bvlmm <- function(X, Bhat, Y, Sigma){
  stopifnot(det(Sigma) > 0, nrow(Sigma) == nrow(X))
  out<- mvtnorm::dmvnorm(as.vector(Y), mean = X %*% Bhat, sigma = Sigma, log = TRUE)
  return(out)
}
