# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_sqrt <- function(A) {
    .Call('_qtl2pleio_rcppeigen_sqrt', PACKAGE = 'qtl2pleio', A)
}

rcppeigen_invsqrt <- function(A) {
    .Call('_qtl2pleio_rcppeigen_invsqrt', PACKAGE = 'qtl2pleio', A)
}

timesTwo <- function(x) {
    .Call('_qtl2pleio_timesTwo', PACKAGE = 'qtl2pleio', x)
}

rcpp_ols <- function(X, Y) {
    .Call('_qtl2pleio_rcpp_ols', PACKAGE = 'qtl2pleio', X, Y)
}

rcpp_gls <- function(X, Y, Sigma_inv) {
    .Call('_qtl2pleio_rcpp_gls', PACKAGE = 'qtl2pleio', X, Y, Sigma_inv)
}

rcppeigen_invert_matrix <- function(A) {
    .Call('_qtl2pleio_rcppeigen_invert_matrix', PACKAGE = 'qtl2pleio', A)
}

rcppeigen_get_diag <- function(A) {
    .Call('_qtl2pleio_rcppeigen_get_diag', PACKAGE = 'qtl2pleio', A)
}

rcppeigen_get_det <- function(A) {
    .Call('_qtl2pleio_rcppeigen_get_det', PACKAGE = 'qtl2pleio', A)
}

rcppeigen_get_chol <- function(A) {
    .Call('_qtl2pleio_rcppeigen_get_chol', PACKAGE = 'qtl2pleio', A)
}

rcppeigen_get_chol_stable <- function(A) {
    .Call('_qtl2pleio_rcppeigen_get_chol_stable', PACKAGE = 'qtl2pleio', A)
}

rcppeigen_get_chol_diag <- function(A) {
    .Call('_qtl2pleio_rcppeigen_get_chol_diag', PACKAGE = 'qtl2pleio', A)
}

